### ISSUE TITLE
interaction with GP AI is VERY SLOW!

### ISSUE THREAD

**Issue by spaceda1** [TimNekk/Gigapixel#15]
Hi
just tested few operations and looks like managing GP is running very slowly where image operations on GP level are typical quite fast.
commands are sent to GP with huge pauses between steps.
any idea ?
GP AI 6.3.3.
Python 3.9.10 (main, Jan 25 2022, 17:58:23)  [GCC 11.2.0 64 bit (AMD64)] on win32

**Comment by Wulfheart1** [comment]
i can confirm that it sometimes works much slower as it could be to load the image, set the settings and start processing (~1 Minute), but sometimes it even gets much worse, then it takes minutes easily to complete each step and sometimes it even throws a timeout error. In the last two days it had this behaviour, today without any change it works again with normal slow performance. 

Changing to win32 backend speeds up the application performance heavily but then it doesn't find the buttons. So one way to solve this might be to change to win32 backend

**Comment by TimNekk** [comment]
Will try to optimize in near future. Thanks for feedback.

**Comment by TimNekk** [comment]
Read #17 to learn optimizations. 60% faster now.
