### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by pavel-rossinsky** [TimNekk/Gigapixel#18]
In the configuration of the package it says Operating System
[OS Independent](https://pypi.org/search/?c=Operating+System+%3A%3A+OS+Independent). However, you can run the package only on Windows. When trying to run on MacOS, the error occurs:
Traceback (most recent call last):
 
    from pywinauto import ElementNotFoundError, timings
ImportError: cannot import name 'ElementNotFoundError' from 'pywinauto' (/image-upscaler/venv/lib/python3.11/site-packages/pywinauto/__init__.py)

Process finished with exit code 1

This is clear since pywinauto works only on Windows.

**Comment by TimNekk** [comment]
Thx for noticing  =)
