### ISSUE TITLE
compatibility issue with 7.14 and probably above

### ISSUE THREAD

**Issue by rodolphehoa** [TimNekk/Gigapixel#26]
Hi, I tried with 6.3 and yeah ! Neat, very useful script !

But I am unable to make it work with 7.14.
The ui open but the image won't load, probably due to the massive update topaz did.

If you are already aware of the problem do you plan to update the script in the future ?

<img width="853" alt="image" src="https://github.com/user-attachments/assets/5c3c7d72-217a-4a77-a332-1827a7fdc495">

**Comment by TimNekk** [comment]
Yeah, I will look torwards it. Thanks for report.

**Comment by TimNekk** [comment]
Just tested on Gigapixel v7.2.3 and everything works fine.

Try opening Gigapixel manually first and then run script.
